// Generated by CoffeeScript 1.4.0

angular.module('slider', []).directive("slider", function() {
  return {
    restrict: 'EA',
    scope: {
      min: "@",
      max: "@",
      step: "@",
      value1: "=",
      value2: "="
    },
    link: function(scope, element, attrs) {
      var range, values;
      range = !!scope.value1 && !!scope.value2; 
      if ( range ) {
        values = [scope.value1,scope.value2]
      } else {
        values = [scope.value1]
      }
      return element.slider({
        range: range,
        min: attrs.min,
        max: attrs.max,
        step: new Number(attrs.step),
        values: values,
        slide: function(event, ui) {
          scope.value1 = ui.values[0];
          if (range) {
            scope.value2 = ui.values[1];
          }
          return scope.$apply();
        }
      });
    }
  };
});
