// Generated by CoffeeScript 1.4.0

angular.module('slider', []).directive("slider", function() {
  return {
    restrict: 'EA',
    scope: {
      options: "="
    },
    link: function(scope, element, attrs) {
      var range;
      range = !!scope.options.handle1 && !!scope.options.handle2;
      return element.slider({
        range: range,
        min: scope.options.min,
        max: scope.options.max,
        step: scope.options.step,
        values: range ? [scope.options.handle1, scope.options.handle2] : [scope.options.handle1],
        slide: function(event, ui) {
          scope.options.handle1 = ui.values[0];
          if (range) {
            scope.options.handle2 = ui.values[1];
          }
          scope.$apply();
        }
      });
    }
  };
});
